Added code and tests
jhlfrfufyfn/MatrixProcessing pull request #1
Opened 2020-09-15 18:57 UTC by jhlfrfufyfn

It's my second Java assignment, variant 8:

"Найти номер строки заданной матрицы, в которой находится самая длинная серия (последовательность одинаковых элементов)."

2020-09-15 19:43 UTC, VeronikaYastr requested changes

2020-09-15 19:43 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +package com.bsu;
У тебя форматирование полетело, склеились символы
Ctrl+Alt+L в идее надо нажать, чтобы все выровнять

2020-09-15 19:43 UTC, VeronikaYastr commented on src/com/bsu/Main.java
> +            if(n < 0){
Хм, а если равно 0, то это разве валидный вариант?)

2020-09-16 15:51 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +            if(n < 0){
Исправлено

2020-09-16 15:51 UTC, jhlfrfufyfn commented on src/com/bsu/Main.java
> +package com.bsu;
Исправлено

2020-09-16 15:56 UTC, VeronikaYastr commented
Можно мержить🙂

2020-09-16 16:36 UTC, merged